#!/usr/bin/env python3
#
# Copyright (c) 2020 by Clemens Rabe <clemens.rabe@clemensrabe.de>
# All rights reserved.
# This file is part of powercounter (https://github.com/seeraven/powercounter)
# and is released under the "BSD 3-Clause License". Please see the LICENSE file
# that is included as part of this package.
#
"""Power counter main entry point."""


# -----------------------------------------------------------------------------
# Module Import
# -----------------------------------------------------------------------------
import sys

from power_counter.command import power_counter

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(0 if power_counter() else 1)
